-- ===============================
-- ESTADOS
-- ===============================
INSERT INTO ESTADOS_AUTOBUS (ID, NOMBRE) VALUES (1, 'OPERATIVO');
INSERT INTO ESTADOS_AUTOBUS (ID, NOMBRE) VALUES (2, 'TALLER');
INSERT INTO ESTADOS_AUTOBUS (ID, NOMBRE) VALUES (3, 'FUERA_SERVICIO');

-- ===============================
-- AUTOBUSES
-- ===============================

INSERT INTO AUTOBUSES (AUTOBUS_ID, MATRICULA, BASTIDOR, ESTADO_ID, FLOTA)
VALUES (100, '1234ABC', 'BAST-001', 1, 'URBANA');

INSERT INTO AUTOBUSES (AUTOBUS_ID, MATRICULA, BASTIDOR, ESTADO_ID, FLOTA)
VALUES (101, '5678DEF', 'BAST-002', 1, 'URBANA');

INSERT INTO AUTOBUSES (AUTOBUS_ID, MATRICULA, BASTIDOR, ESTADO_ID, FLOTA)
VALUES (102, '9012GHI', 'BAST-003', 2, 'INTERURBANA');

INSERT INTO AUTOBUSES (AUTOBUS_ID, MATRICULA, BASTIDOR, ESTADO_ID, FLOTA)
VALUES (103, '3456JKL', 'BAST-004', 3, 'INTERURBANA');

INSERT INTO AUTOBUSES (AUTOBUS_ID, MATRICULA, BASTIDOR, ESTADO_ID, FLOTA)
VALUES (104, '7890MNO', 'BAST-005', 1, 'ESCOLAR');

INSERT INTO AUTOBUSES (AUTOBUS_ID, MATRICULA, BASTIDOR, ESTADO_ID, FLOTA)
VALUES (105, '1122PQR', 'BAST-006', 2, 'ESCOLAR');

INSERT INTO AUTOBUSES (AUTOBUS_ID, MATRICULA, BASTIDOR, ESTADO_ID, FLOTA)
VALUES (106, '3344STU', 'BAST-007', 1, 'URBANA');
